# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Debian-Package-Make
version:      0.04
version_from: lib/Debian/Package/Make.pm
installdirs:  site
requires:
    Cwd:                           0
    Dpkg::Arch:                    0
    Dpkg::Cdata:                   0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Temp:                    0
    IPC::Run:                      0
    LWP::Simple:                   0
    Text::Wrap:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
